package com.mikhalych.storage_of_autoparts.models.enums;

public enum Catalogs {ENGINE, FUEL_SYSTEM, COOLING_SYSTEM, EXHAUST_SYSTEM, TRANSMISSION, BRAKE_SYSTEM, ELECTRIC_SYSTEM,
    BODY_PARTS, INTERIOR_DETAILS, CHASSIS, STEERING_CONTROL}
